//
//  Mixpanel-Swift.h
//  Runner
//
//  Created manually to fix build issues.
//

// This file is a workaround for the missing Mixpanel-Swift.h header
// The actual content will be generated by the Swift compiler

#ifndef Mixpanel_Swift_h
#define Mixpanel_Swift_h

// Forward declarations of Mixpanel classes
@class MixpanelInstance;
@class People;
@class Group;

#endif /* Mixpanel_Swift_h */ 