name: savie
repository: https://github.com/your-org/savie

packages:
  - .
  - packages/**

scripts:
  analyze:
    description: Analyze the code.
    run: |
      flutter analyze --no-fatal-infos
    exec:
      concurrency: 1

  test:
    description: Run tests in this project.
    run: |
      flutter test
    exec:
      concurrency: 1

  bootstrap:
    description: Bootstrap the project.
    run: |
      melos exec -- flutter pub get

  build:ios:
    description: Build the iOS app.
    run: |
      flutter build ios --no-codesign
    exec:
      concurrency: 1

  format:
    description: Format the code.
    run: |
      dart run import_sorter:main
      flutter format .
    exec:
      concurrency: 1 