name: savie
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+6

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^10.0.1
  get_it: ^8.0.3
  injectable: ^2.4.2
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.1
  uuid: ^4.0.0
  file_picker: ^10.1.2
  collection: ^1.18.0
  record: ^6.0.0
  path_provider: ^2.1.4
  blobs: ^2.0.0
  wave_blob: ^1.0.5
  permission_handler: ^12.0.0+1
  audioplayers: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  photo_manager: ^3.2.0
  flutter_cache_manager: ^3.3.2
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  status_bar_control: ^3.2.1
  flutter_sticky_header:
    git:
      url: https://github.com/charlesRmajor/flutter_sticky_header.git
  supabase_flutter: ^2.5.8
  firebase_core: ^3.2.0
  # Temporarily comment out Google Sign-In to focus on Mixpanel
  # google_sign_in: ^6.1.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  email_validator: ^3.0.0
  pinput: ^5.0.0
  either_dart: ^1.0.0
  gradient_borders: ^1.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  favicon: ^1.1.2
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  in_app_notification: ^1.1.2
  share_plus: ^11.0.0
  rx_shared_preferences: ^4.0.0
  rxdart: ^0.28.0
  floating_draggable_widget: ^2.1.5
  retrofit: ^4.1.0
  mixpanel_flutter: ^2.3.1
  appmetrica_plugin: ^3.1.0
  logger: ^2.4.0
  hive: ^2.2.3
  cached_network_image: ^3.3.1
  pdf_render: ^1.4.12
  image: ^4.2.0
  animated_list_plus: ^0.5.2
  positioned_scroll_observer: ^2.2.2
  sortedmap: ^0.5.4
  animated_size_and_fade: ^5.1.1
  percent_indicator: ^4.2.3
  open_file: ^3.3.2
  gal: ^2.3.0
  receive_sharing_intent: ^1.8.0
  flutter_native_splash: ^2.4.1
  desktop_drop:
    git:
      url: https://github.com/galt-agency/flutter-plugins.git
      ref: feature/file-formats
      path: packages/desktop_drop
  package_info_plus: ^8.1.1
  window_manager: ^0.4.3
  tray_manager: ^0.5.0
  native_dialog_plus:
    git:
      url: https://github.com/galt-agency/native_dialog_plus.git
  flutter_quill: 
    path: ../flutter-quill
  flutter_localization: ^0.3.2
  vsc_quill_delta_to_html: ^1.0.5
  pasteboard: ^0.4.0
  accessing_security_scoped_resource: ^3.2.0
  measured_size: ^1.0.0
  gesture_x_detector: 1.1.1
  mocktail: ^1.0.4
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9

dependency_overrides:
  # https://github.com/google/GoogleSignIn-iOS/issues/165
  # google_sign_in_ios: 5.5.0

flutter_gen:
  output: lib/presentation/shared/assets/

  integrations:
    flutter_svg: true


flutter_native_splash:
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/

  fonts:
    - family: New York Large
      fonts:
        - asset: fonts/new_york_large/NewYorkLarge-Black.otf
          weight: 900
        - asset: fonts/new_york_large/NewYorkLarge-BlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/new_york_large/NewYorkLarge-Bold.otf
          weight: 700
        - asset: fonts/new_york_large/NewYorkLarge-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/new_york_large/NewYorkLarge-Heavy.otf
          weight: 800
        - asset: fonts/new_york_large/NewYorkLarge-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/new_york_large/NewYorkLarge-Medium.otf
          weight: 500
        - asset: fonts/new_york_large/NewYorkLarge-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/new_york_large/NewYorkLarge-Regular.otf
          weight: 400
        - asset: fonts/new_york_large/NewYorkLarge-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/new_york_large/NewYorkLarge-Semibold.otf
          weight: 600
        - asset: fonts/new_york_large/NewYorkLarge-SemiboldItalic.otf
          weight: 600
          style: italic

    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Thin.ttf
          weight: 100

    - family: SF Mono
      fonts:
        - asset: fonts/sf_mono/SFMono-Bold.otf
          weight: 700
        - asset: fonts/sf_mono/SFMono-Heavy.otf
          weight: 800
        - asset: fonts/sf_mono/SFMono-Light.otf
          weight: 300
        - asset: fonts/sf_mono/SFMono-Medium.otf
          weight: 500
        - asset: fonts/sf_mono/SFMono-Regular.otf
          weight: 400
        - asset: fonts/sf_mono/SFMono-Semibold.otf
          weight: 600

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icon_macos.png"